'use client';

import { useRef, useState, type FormEvent, type ReactNode } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Markdown } from '@/components/markdown';
import { EMAIL_NOT_CONFIRMED, showConfirmationResend } from '@/lib/auth-flow';
import { useI18n } from '@/components/i18n';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { saveProblem, saveSolution, saveHack, saveProfile, signIn, signUp, resendConfirmation } from '@/app/actions';
import type { ActionResult, Hack, Problem, Profile, Solution } from '@/lib/types';

type Action = (data: FormData) => Promise<ActionResult>;
function useSubmit() {
  const router = useRouter(); const lock = useRef(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const submit = async (event: FormEvent<HTMLFormElement>, action: Action, next: (result: Extract<ActionResult, { ok: true }>) => void) => {
    event.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); setError(''); setSuccess('');
    try { const result = await action(new FormData(event.currentTarget)); if (result.ok) { next(result); router.refresh(); } else setError(result.error); }
    catch { setError('formFailed'); }
    finally { lock.current = false; setBusy(false); }
  };
  return { busy, error, setError, success, setSuccess, submit, router };
}
function Feedback({ error, success }: { error: string; success?: string }) {
  const { t } = useI18n();
  return <>{error && <p role="alert" className="rounded-lg border border-rose-400/30 bg-rose-500/10 px-3 py-2 text-sm text-rose-300">{error === 'formFailed' ? t('formFailed') : error === EMAIL_NOT_CONFIRMED ? t('emailNotConfirmed') : error}</p>}{success && <p role="status" className="rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-sm text-emerald-300">{success}</p>}</>;
}
function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="block space-y-1.5"><span className="text-sm font-medium text-ink">{label}</span>{children}{hint && <span className="block text-xs text-muted">{hint}</span>}</label>; }
export function MarkdownEditor({ name, label, initial = '', required = false, rows = 12 }: { name: string; label: string; initial?: string; required?: boolean; rows?: number }) {
  const { t } = useI18n(); const [value, setValue] = useState(initial); const [preview, setPreview] = useState(false);
  return <div><div className="mb-2 flex items-center justify-between gap-3"><label htmlFor={name} className="text-sm font-medium text-ink">{label}</label><div className="flex rounded-lg border border-edge bg-panel-elevated p-0.5 text-xs"><button type="button" onClick={() => setPreview(false)} className={`rounded-md px-3 py-1.5 ${!preview ? 'bg-panel font-medium text-ink shadow-sm' : 'text-muted'}`}>{t('write')}</button><button type="button" onClick={() => setPreview(true)} className={`rounded-md px-3 py-1.5 ${preview ? 'bg-panel font-medium text-ink shadow-sm' : 'text-muted'}`}>{t('preview')}</button></div></div><Textarea id={name} name={name} required={required} rows={rows} value={value} onChange={e => setValue(e.target.value)} className={preview ? 'sr-only' : 'font-mono text-[13px]'} /><div className={preview ? 'min-h-44 rounded-lg border border-edge bg-panel p-4' : 'hidden'}>{value ? <Markdown>{value}</Markdown> : <p className="text-sm text-muted">{t('previewEmpty')}</p>}</div><p className="mt-1 text-xs text-muted">{t('markdownHint')}</p></div>;
}
export function ProblemForm({ problem }: { problem?: Problem }) {
  const { t } = useI18n(); const state = useSubmit();
  return <form onSubmit={e => state.submit(e, saveProblem, result => state.router.push(result.redirectTo || `/problems/${result.id || problem?.id}`))} className="mx-auto max-w-3xl space-y-6 rounded-xl border border-edge bg-panel p-5 sm:p-8"><h1 className="text-2xl font-bold text-ink">{t(problem ? 'editProblemTitle' : 'newProblemTitle')}</h1><fieldset disabled={state.busy} className="space-y-5">{problem && <input type="hidden" name="id" value={problem.id}/>}<Field label={t('title')}><Input name="title" required maxLength={200} defaultValue={problem?.title || ''} placeholder={t('titlePlaceholder')}/></Field><div className="grid gap-5 sm:grid-cols-2"><Field label={t('source')}><Input name="source" maxLength={100} defaultValue={problem?.source || ''} placeholder={t('sourcePlaceholder')}/></Field><Field label={t('difficulty')}><select name="difficulty" defaultValue={problem?.difficulty || 'medium'} className="h-10 w-full rounded-lg border border-edge bg-panel-elevated px-3 text-sm text-ink focus:border-electric focus:ring-2 focus:ring-electric/20"><option value="easy">{t('easy')}</option><option value="medium">{t('medium')}</option><option value="hard">{t('hard')}</option></select></Field></div><Field label={t('externalUrl')}><Input name="external_url" type="url" defaultValue={problem?.external_url || ''} placeholder={t('externalUrlPlaceholder')}/></Field><Field label={t('tags')}><Input name="tags" defaultValue={problem?.tags?.join(', ') || ''} placeholder={t('tagsPlaceholder')}/></Field><MarkdownEditor name="statement_md" label={t('statementLabel')} initial={problem?.statement_md || ''} required/><Feedback error={state.error}/><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => state.router.back()}>{t('cancel')}</Button><Button type="submit" disabled={state.busy}>{state.busy ? t('saving') : t('save')}</Button></div></fieldset></form>;
}
export function SolutionForm({ solution, problemId }: { solution?: Solution; problemId: string }) {
  const { t } = useI18n(); const state = useSubmit();
  return <form onSubmit={e => state.submit(e, saveSolution, result => state.router.push(result.redirectTo || `/solutions/${result.id || solution?.id}`))} className="mx-auto max-w-3xl space-y-6 rounded-xl border border-edge bg-panel p-5 sm:p-8"><h1 className="text-2xl font-bold text-ink">{t(solution ? 'editSolutionTitle' : 'newSolutionTitle')}</h1><fieldset disabled={state.busy} className="space-y-5"><input type="hidden" name="problem_id" value={problemId}/>{solution && <input type="hidden" name="id" value={solution.id}/>}<Field label={t('title')}><Input name="title" required maxLength={200} defaultValue={solution?.title || ''} placeholder={t('solutionTitlePlaceholder')}/></Field><div className="grid gap-5 sm:grid-cols-2"><Field label={t('algorithm')}><Input name="algorithm" defaultValue={solution?.algorithm || ''} placeholder={t('algorithmPlaceholder')}/></Field><Field label={t('languageLabel')}><Input name="language" defaultValue={solution?.language || ''} placeholder={t('languagePlaceholder')}/></Field><Field label={t('timeComplexity')}><Input name="time_complexity" defaultValue={solution?.time_complexity || ''} placeholder={t('complexityPlaceholder')}/></Field><Field label={t('spaceComplexity')}><Input name="space_complexity" defaultValue={solution?.space_complexity || ''} placeholder={t('complexityPlaceholder')}/></Field></div><MarkdownEditor name="content_md" label={t('contentLabel')} initial={solution?.content_md || ''} required/><Field label={t('codeOptional')}><Textarea name="code" rows={12} defaultValue={solution?.code || ''} className="font-mono text-xs" spellCheck={false}/></Field><Feedback error={state.error}/><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => state.router.back()}>{t('cancel')}</Button><Button type="submit" disabled={state.busy}>{state.busy ? t('saving') : t('save')}</Button></div></fieldset></form>;
}
export function HackForm({ hack, solutionId }: { hack?: Hack; solutionId: string }) {
  const { t } = useI18n(); const state = useSubmit();
  return <form onSubmit={e => state.submit(e, saveHack, result => state.router.push(result.redirectTo || `/solutions/${solutionId}`))} className="mx-auto max-w-3xl space-y-6 rounded-xl border border-edge bg-panel p-5 sm:p-8"><div><h1 className="text-2xl font-bold text-ink">{t(hack ? 'editHackTitle' : 'newHackTitle')}</h1><p className="mt-2 text-sm text-muted">{t('hackHint')}</p></div><fieldset disabled={state.busy} className="space-y-5"><input type="hidden" name="solution_id" value={solutionId}/>{hack && <input type="hidden" name="id" value={hack.id}/>}<Field label={t('hackType')}><select name="type" defaultValue={hack?.type || 'counterexample'} className="h-10 w-full rounded-lg border border-edge bg-panel-elevated px-3 text-sm text-ink focus:border-electric focus:ring-2 focus:ring-electric/20"><option value="counterexample">{t('counterexample')}</option><option value="logic">{t('logic')}</option><option value="complexity">{t('complexity')}</option><option value="boundary">{t('boundary')}</option></select></Field><MarkdownEditor name="content_md" label={t('hackContentLabel')} initial={hack?.content_md || ''} required rows={8}/><div className="grid gap-5 sm:grid-cols-2"><Field label={t('inputData')}><Textarea name="input_data" rows={5} defaultValue={hack?.input_data || ''} className="font-mono text-xs"/></Field><Field label={t('expectedOutput')}><Textarea name="expected_output" rows={5} defaultValue={hack?.expected_output || ''} className="font-mono text-xs"/></Field></div><Field label={t('actualOutput')}><Textarea name="actual_output" rows={5} defaultValue={hack?.actual_output || ''} className="font-mono text-xs"/></Field><Feedback error={state.error}/><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => state.router.back()}>{t('cancel')}</Button><Button type="submit" disabled={state.busy}>{state.busy ? t('saving') : t('submit')}</Button></div></fieldset></form>;
}
export function AuthForm({ mode, redirectTo, confirmationError = false }: { mode: 'login' | 'register'; redirectTo: string; confirmationError?: boolean }) {
  const { t } = useI18n(); const state = useSubmit();
  const formRef = useRef<HTMLFormElement>(null); const resendLock = useRef(false); const [resendBusy, setResendBusy] = useState(false); const [resendError, setResendError] = useState(''); const [resendSuccess, setResendSuccess] = useState(false);
  const resend = async () => {
    if (resendLock.current) return;
    const email = formRef.current?.elements.namedItem('email') as HTMLInputElement | null;
    if (!email || !email.reportValidity()) return;
    resendLock.current = true; setResendBusy(true); setResendError(''); setResendSuccess(false);
    const data = new FormData(); data.set('email', email.value); data.set('redirectTo', redirectTo);
    try { const result = await resendConfirmation(data); if (result.ok) setResendSuccess(true); else setResendError(result.error); }
    catch { setResendError(t('formFailed')); }
    finally { resendLock.current = false; setResendBusy(false); }
  };
  const onSubmit = (event: FormEvent<HTMLFormElement>) => state.submit(event, mode === 'login' ? signIn : signUp, result => { if (mode === 'register') state.setSuccess(result.message || t('checkEmail')); else state.router.push(result.redirectTo || '/'); });
  return <form ref={formRef} onSubmit={onSubmit} className="mx-auto max-w-md space-y-5 rounded-xl border border-edge bg-panel p-6 shadow-sm sm:p-8"><div><h1 className="text-2xl font-bold text-ink">{t(mode === 'login' ? 'loginTitle' : 'registerTitle')}</h1><p className="mt-2 text-sm text-muted">{t(mode === 'login' ? 'loginHint' : 'registerHint')}</p></div>{confirmationError && <p role="alert" className="rounded-lg border border-rose-400/30 bg-rose-500/10 p-3 text-sm text-rose-300">{t('confirmError')}</p>}<fieldset disabled={state.busy} className="space-y-4"><input type="hidden" name="redirectTo" value={redirectTo}/>{mode === 'register' && <Field label={t('username')} hint={t('userNameHint')}><Input name="username" autoComplete="username" pattern="[a-z0-9_]+" minLength={3} maxLength={32} required/></Field>}<Field label={t('email')}><Input name="email" type="email" autoComplete="email" required/></Field><Field label={t('password')}><Input name="password" type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} minLength={mode === 'register' ? 8 : undefined} required/></Field><Feedback error={state.error} success={state.success}/><Button type="submit" className="w-full" disabled={state.busy}>{state.busy ? t('submitting') : t(mode === 'login' ? 'login' : 'register')}</Button>{showConfirmationResend(confirmationError, !!state.success, state.error) && <div className="space-y-2 border-t border-edge pt-4"><Button type="button" variant="secondary" className="w-full" onClick={resend} disabled={resendBusy}>{resendBusy ? t('submitting') : t('resendConfirmation')}</Button>{resendError && <p role="alert" className="text-sm text-rose-300">{resendError}</p>}{resendSuccess && <p role="status" className="text-sm text-electric">{t('resendSent')}</p>}</div>}</fieldset><p className="text-center text-sm text-muted">{t(mode === 'login' ? 'noAccount' : 'hasAccount')} <Link href={mode === 'login' ? `/register?next=${encodeURIComponent(redirectTo)}` : `/login?next=${encodeURIComponent(redirectTo)}`} className="font-medium text-electric hover:underline">{t(mode === 'login' ? 'register' : 'login')}</Link></p></form>;
}
export function ProfileForm({ profile }: { profile: Profile }) {
  const { t } = useI18n(); const state = useSubmit();
  return <form onSubmit={e => { void state.submit(e, saveProfile, result => state.router.push(result.redirectTo || `/profile/${encodeURIComponent(profile.username)}`)); }} className="mx-auto max-w-xl space-y-5 rounded-xl border border-edge bg-panel p-6 sm:p-8"><h1 className="text-2xl font-bold text-ink">{t('profileEditTitle')}</h1><fieldset disabled={state.busy} className="space-y-5"><Field label={t('username')} hint={t('userNameHint')}><Input name="username" required minLength={3} maxLength={32} pattern="[a-z0-9_]+" defaultValue={profile.username}/></Field><Field label={t('avatarUrl')}><Input name="avatar_url" type="url" defaultValue={profile.avatar_url || ''} placeholder="https://…"/></Field><Feedback error={state.error}/><Button type="submit" disabled={state.busy}>{state.busy ? t('saving') : t('save')}</Button></fieldset></form>;
}
